### PR TITLE
Fix options not merging nested default options

### PR DESCRIPTION
**Pull request by Almouro**
Hello!

I think it would be expected as a user to create a Frisbee object like so:
```
new Frisbee({ stringify: { arrayFormat: "repeat" } });
```
without needing to pass the other default options included in `stringify`

Submitting this PR to fix this!

### CODE REVIEW

**Comment by niftylettuce** [comment]
I think we should use https://github.com/jonschlinkert/defaults-deep instead on the options, and then we can do a major version bump.

**Comment by niftylettuce** [comment]
Could you adjust your PR to use this package?

**Comment by Almouro** [comment]
@niftylettuce here's the change but I get an issue https://travis-ci.org/niftylettuce/frisbee/jobs/587049093#L253 with the linting on `defaults-deep` added in the `dist` folder

Should the `dist` folder really be linted?

**Comment by PierreCapo** [comment]
sorry for the ping, but any news on that @niftylettuce ?

**Comment by niftylettuce** [comment]
I am working on this now

**Comment by niftylettuce** [comment]
I am re-opening this because I am not merging in defaults-deep into the package just yet.  I think we need to be selective about which properties get deeply merged versus all options as this PR had.  Feel free to share thoughts.  I also looked into using <https://www.npmjs.com/package/deepmerge>.

**Pull request merged**
