### PR TITLE
Feature/abortable fetch

### PR DESCRIPTION
**Pull request by akmjenkins**
Adds #3 

Hi there maintainer! I've got an abortable fetch API for you.

The following is important to note:

In order to get the following pattern to work:
```
const req = frisbee.get('/',{abortToken:'some token'});
...
frisbee.abort('some token')
...
try {
  const res = await req;
}
```
the abort-y things cannot be registered asynchronously (i.e. after interceptors), which is why this change **appears** so drastic - it's really not. The majority of it simply moved the async function call in _setup down so I could do some sync stuff first.

Because of the change above, I also had to slightly change the (internal) behavior of registering interceptors and change a few test stubs in interceptor.test.js. Other than adding a dozen tests or so, no other tests were modified and they all still pass, yay!

Coles notes:

* It supports Abortable Fetches using [AbortController and signal ](https://developer.mozilla.org/en-US/docs/Web/API/AbortController)
* abortAll() - does exactly what it says - aborts any running or queued (await-ing in an interceptor*) requests
* An "enhanced" abort API that uses "tokens" - pass in an abortToken (any symbol) on your options and use it to cancel any running request(s) - yes, it can be more than one - that use that token. The ability to cancel more than one request is useful if you want to make a request in an interceptor, just use the same abortToken that's being passed in with the request options.

You've got a good library going here. Quite light weight (as it should), couple of nifty features ("automagic" jwt and auth). I hope abortable fetches, especially this new abort-by-token API will further people's interest in it.

Feedback very much welcome and appreciated. I'm not too big of an open-source contributor so I hope I'm doing it right.

### CODE REVIEW

**Comment by niftylettuce** [comment]
@akmjenkins thank you so much for your efforts here in improving this package and contributing to open source.  I plan to review this tomorrow.  If you don't hear from me by tomorrow feel free to ping me here or at niftylettuce@gmail.com.  Thanks!!!! 👏

**Comment by niftylettuce** [comment]
Hmm, I really don't think this is very user-friendly.  Curious what others think... the purpose of the API is to be incredibly simple and as close to fetch as possible.

**Comment by davidgovea** [comment]
First of all @akmjenkins  -- I want to say that I like the design approach taken here: complies with the standard, and adds some convenience on top. Looks like the `abortToken` is similar to axios' `cancelToken`, and the abortAll is comfortable API.

However, one thing I'm concerned about is that this **isn't true cancellation**: the [abortcontroller-polyfill](https://github.com/mo/abortcontroller-polyfill) says it's a:

> stub that calls catch, doesn't actually abort request

This, plus the limitations on cancelling GET requests only, and the observation that you made about frisbee _already supporting AbortController signals_, makes me think that maybe this shouldn't go into frisbee.

Cancellation & concurrency is harddd -- I've been using generator-based solutions, because generators can actually be cancelled, unlike async functions or promise chains. [ember-concurrency](http://ember-concurrency.com/docs/introduction/) is my favorite. I'm getting used to [redux-saga](https://redux-saga.js.org/) on the react side, and I've also done a bit of work with [posterus](https://github.com/mitranim/posterus), which is also pretty fantastic. However, it's clear that there is a lot of responsibility still left to the developer, with or without this change.

Even things like timeouts might be best handled _outside_ of frisbee. 

---

Still going to do some thinking here, but wanted to jot these thoughts down

**Comment by davidgovea** [comment]
You bring up some great points. Thanks for the link - I haven't kept up on these topics.

I'm in favor of this PR. I think it's quite user-friendly, considering the sophistication of cancellation in general. It's faithful to the standards, enables AbortController use on all platforms, and provides some nice convenience on top. 

My last consideration is making sure everything works on react-native, since that's one of the main selling points of frisbee over other libraries.

**Comment by niftylettuce** [comment]
@akmjenkins @davidgovea @tb9-Mason I've merged this PR, fixed all tests, and cleaned up the entire codebase.  Please try out `v2.0.10` just released to NPM! 🎉 🎉 🎉 

```sh
npm install frisbee@latest
```

```sh
yarn add frisbee@latest
```

**Pull request merged**
